/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mn23300216.pkg21;

import javax.swing.JFrame;
import java.util.LinkedList;
import java.awt.event.*;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Daimo
 */
public class MostrarTexto extends javax.swing.JFrame {
        int i;
        private static LinkedList<String> colaMet;
        private static LinkedList<String> tiempoCola;
        private boolean edit = false;
        private boolean export = false;
        FileWriter file = null;
    /**
     * Creates new form MostrarTexto
     */
    public MostrarTexto() {
        initComponents();
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fileMenuBar = new javax.swing.JMenuBar();
        fileExport = new javax.swing.JMenu();
        textEdit = new javax.swing.JMenu();
        saveTextButton = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        saveTextGG = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        saveNameButton = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        showTextField.setActionCommand("<Not Set>");

        backButton.setText("<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        nextButton.setText(">");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        infoLabel.setText("Se agrego a las:");

        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });

        jLabel1.setText("ingresa el nombre del archivo aqui ->");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        fileExport.setText("Exportar");
        fileExport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileExportMouseClicked(evt);
            }
        });
        fileMenuBar.add(fileExport);

        textEdit.setText("Editar");
        textEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textEditMouseClicked(evt);
            }
        });
        fileMenuBar.add(textEdit);

        saveTextButton.setText("Guardar");
        saveTextButton.setEnabled(false);
        saveTextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveTextButtonMouseClicked(evt);
            }
        });
        saveTextButton.add(jSeparator2);

        saveTextGG.setText("Guardar");
        saveTextGG.setEnabled(false);
        saveTextGG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveTextGGMouseClicked(evt);
            }
        });
        saveTextButton.add(saveTextGG);
        saveTextButton.add(jSeparator1);

        saveNameButton.setText("Guardar Nombre");
        saveNameButton.setEnabled(false);
        saveNameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveNameButtonMouseClicked(evt);
            }
        });
        saveTextButton.add(saveNameButton);
        saveTextButton.add(jSeparator3);

        fileMenuBar.add(saveTextButton);

        setJMenuBar(fileMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(backButton)
                .addGap(49, 49, 49)
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(nextButton)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showTextField)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addComponent(showTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(nextButton)
                    .addComponent(infoLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        if(i!=colaMet.size()-1){
            i++;
            export = false;
            jLabel1.setVisible(false);
            jTextArea1.setVisible(false);
            showTextField.setEditable(false);
            saveTextButton.setEnabled(false);
            showTextField.setText(colaMet.get(i));
            infoLabel.setText("Se agrego a las >" + tiempoCola.get(i));
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        if(i>0){
            i --;
            export = false;
            jLabel1.setVisible(false);
            jTextArea1.setVisible(false);
            showTextField.setEditable(false);
            showTextField.setText(colaMet.get(i));
            infoLabel.setText("Se agrego a las >" + tiempoCola.get(i));
            saveTextButton.setEnabled(false);
        }   
    }//GEN-LAST:event_backButtonActionPerformed

    private void fileExportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileExportMouseClicked
        // TODO add your handling code here:
        export = true;
        jLabel1.setVisible(true);
        jTextArea1.setVisible(true);
        saveTextButton.setEnabled(true);
    }//GEN-LAST:event_fileExportMouseClicked

    private void textEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEditMouseClicked
        // TODO add your handling code here:
        edit = true;
        showTextField.setEditable(true);
        saveTextButton.setEnabled(true);
        
    }//GEN-LAST:event_textEditMouseClicked

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void saveTextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveTextButtonMouseClicked
        // TODO add your handling code here:
        if(edit==true)
            saveTextGG.setEnabled(true);
        if(export==true)
            saveNameButton.setEnabled(true);
    }//GEN-LAST:event_saveTextButtonMouseClicked

    private void saveNameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveNameButtonMouseClicked
        // TODO add your handling code here:
        try{
            if(!jTextArea1.getText().equals("")){
                file = new FileWriter("C:/Users/Daimo/Desktop/"+ jTextArea1.getText()+".txt");
                file.write(showTextField.getText());
                file.close();   
            }
            else
               JOptionPane.showMessageDialog(null, "El archivo no tiene nombre");
        }catch(Exception ex){
            System.out.println("Excepcion D:");
        }
    }//GEN-LAST:event_saveNameButtonMouseClicked

    private void saveTextGGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveTextGGMouseClicked
        // TODO add your handling code here:
        colaMet.set(i, showTextField.getText());
    }//GEN-LAST:event_saveTextGGMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarTexto().setVisible(true);
            }
            
        });
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JMenu fileExport;
    private javax.swing.JMenuBar fileMenuBar;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextField jTextArea1;
    private javax.swing.JButton nextButton;
    private javax.swing.JMenu saveNameButton;
    private javax.swing.JMenu saveTextButton;
    private javax.swing.JMenu saveTextGG;
    private javax.swing.JTextField showTextField;
    private javax.swing.JMenu textEdit;
    // End of variables declaration//GEN-END:variables

        public void setText(LinkedList<String> cola, LinkedList<String> tiempo){
            colaMet = cola;
            tiempoCola = tiempo;
            i = colaMet.size();
            i--;
            showTextField.setEditable(false);
            showTextField.setText(colaMet.get(i));
            infoLabel.setText("Agregado el dia " + tiempoCola.get(i));
            jLabel1.setVisible(false);
            jTextArea1.setVisible(false);
        }
}
